

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    druid:
      url: jdbc:h2:mem:docker_gradle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
      username: sa
      password:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
    user: sa
    password:
    url: jdbc:h2:mem:docker_gradle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    contexts: dev

mybatis:
  configuration:
    database-id: h2